name: Train Random Forest with MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: msml
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow CLI
        run: pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . -P data_path=personality_preprocessing

      - name: Upload MLruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns/

  build-and-push-docker:
    needs: train-model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download logged model artifact
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns

      - name: Debug list model files
        run: ls -R MLProject/mlruns/

      - name: Install MLflow CLI
        run: pip install mlflow

      - name: Build MLflow Docker image
        run: |
          cd MLProject
          MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | head -n 1)
          echo "Found model at: $MODEL_PATH"
          mlflow models build-docker -m $MODEL_PATH

      - name: Tag Docker image
        run: docker tag mlflow-image:latest ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}
