name: Train Random Forest with MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: msml
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow CLI and dependencies
        shell: bash -l {0}
        run: |
          conda install pip -n msml
          conda run -n msml pip install mlflow[extras]

      - name: Run training script with MLflow
        shell: bash -l {0}
        run: |
          conda run -n msml python MLProject/modelling.py --data_path MLProject/personality_preprocessing

      - name: Debug - List mlruns directory
        run: ls -R mlruns

      - name: Upload MLruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

  build-and-push-docker:
    needs: train-model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download logged model artifact
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Debug - List mlruns contents
        run: ls -R mlruns/

      - name: Build MLflow Docker image
        run: |
          MODEL_PATH=$(find mlruns -type d -name "randomforest_model" | head -n 1)
          echo "Found model at: $MODEL_PATH"
          mlflow models build-docker -m $MODEL_PATH --name ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}
